### PR TITLE
Defined moods on all tracks

### PR DESCRIPTION
**Pull request by rvanlaarhoven**
Currently defined three different moods:

- lonely
- romancing
- lovemaking

Also removed a few way too uptempo tracks and adjusted track names to avoid including "remasterd version", "radio edit", etc.

### CODE REVIEW

**Comment by WoutGroenendijk** [comment]
Boooooh!!!! where is erotic?

**Comment by rvanlaarhoven** [comment]
`lovemaking`

**Comment by WoutGroenendijk** [comment]
Oooh dear Rick so young so naive, I understand two complete different things between lovemaking and erotic.

Lovemaking is more sensual and might even come close to romantic...

**Comment by rvanlaarhoven** [comment]
Erotic and lovemaking is the same thing IMO. Seems like you're expecting a genre that's more related to porn. Schuifel Shuffle is meant to be romantic, so i'll stick to `lovemaking` here ;).

**Comment by cecilevdwaal** [comment]
I have a few additional mood suggestions:

- dramatic 
- tragic
- hurt 
- sparkly 
- lovey-dovey
- abandoned
- cheerful
- desperate

What do you think?

**Pull request merged**
